ALTER TABLE notes ADD COLUMN IF NOT EXISTS archived BOOLEAN DEFAULT FALSE;
UPDATE notes SET archived = FALSE WHERE archived IS NULL;
ALTER TABLE notes ALTER COLUMN archived SET DEFAULT FALSE;
ALTER TABLE notes ALTER COLUMN archived SET NOT NULL;
